export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	SET_EVENT_DATA: 'SET_EVENT_DATA',
	RESET_EVENT_DATA: 'RESET_EVENT_DATA',
	ADD_COMMENT: 'ADD_COMMENT',
	REMOVE_COMMENT: 'REMOVE_COMMENT',
	UPDATE_COMMENT: 'UPDATE_COMMENT',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	SET_SEARCH_PHRASE: 'SET_SEARCH_PHRASE',
	SET_IS_LOADING: 'SET_IS_LOADING',
};
